### ISSUE TITLE
Add making build directory to the makefile

### ISSUE THREAD

**Issue by ghuls** [byronknoll/cmix#1]
After cloning the git repository and trying to build cmix, the build fails because the build directory does not exist and is not created by the makefile.
```
$ make
g++ -std=c++11 -Wall -c -Ofast -march=native -s src/preprocess/preprocessor.cpp -o build/preprocessor.o
Assembler messages:
Fatal error: can't create build/preprocessor.o: No such file or directory
make: *** [build/preprocessor.o] Error 1
```
It would be nice if the build directory is automatically created.

**Comment by byronknoll** [comment]
Good idea - done.
