### ISSUE TITLE
missing includes when compiling with g++ 7.2

### ISSUE THREAD

**Issue by sdack** [byronknoll/cmix#11]
There are two #include's missing for cmix to compile with g++ 7.2, which need to be added to src/models/byte-model.h to fix it:

```
#include <numeric> // needed for accumulate()
#include <vector> // defines class std::vector
```
The include for accumulate() should probably go into the .cpp file instead of the header, but either way seems to fix it.

**Comment by byronknoll** [comment]
Thanks for reporting, done.
