### ISSUE TITLE
brew install cmix

### ISSUE THREAD

**Issue by maximveksler** [byronknoll/cmix#2]
Having the tool available through Homebrew can be useful. 

I am currently able to confirm make builds the binary on Mac.

**Comment by byronknoll** [comment]
What is the advantage of Homebrew over make? It seems like make does the same thing, but works on multiple platforms. I don't have a Mac, so it would also be difficult for me to configure/test this.

**Comment by alexpreynolds** [comment]
It is a popular package manager for open-source Unix and scientific software on OS X. There is a version of Homebrew for Linux called Linuxbrew (http://linuxbrew.sh). 

It like `yum` or `get-apt` etc. on Linux, except that it uses Github to make it easier for developers to add and maintain a "recipe" or package manifest, and it generally does not require `sudo` privileges. 

If you make your software available through package managers, it makes it easier to distribute and gain broader adoption, which may or may not be of interest.

**Comment by byronknoll** [comment]
Makes sense - yeah it sounds like it could be useful. However, I don't want to create a Homebrew formula for cmix without having a Mac to test it on. I will keep this issue open in case someone else wants to create it.

**Comment by mfilippov** [comment]
I made PR in Homebrew: https://github.com/Homebrew/homebrew-core/pull/39024

**Comment by mfilippov** [comment]
Homebrew accepted my PR, the issue could be closed.

**Comment by byronknoll** [comment]
Thanks for the help!
