### ISSUE TITLE
std::bad_alloc on Windows

### ISSUE THREAD

**Issue by tazr** [byronknoll/cmix#25]
I am compiling cmix v14 under msys2 (gcc 7.2.0 Rev2).

Compiling works fine and ./cmix prints the help.

However ./cmix -c ./README ./foo (or any other file really) results in 

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```

EDIT

Windows version is Windows 7 64bits

**Comment by byronknoll** [comment]
std::bad_alloc happens when there is failure to allocate storage. How much RAM does your computer have? Do you have a page (or swap) file enabled? If so, what is the max size for the page file?

**Comment by tazr** [comment]
I have 16GB of memory, no pagefile. The README of cmix is not a big file, I would not expect running out of memory in that case?

**Comment by byronknoll** [comment]
16GB is not enough, even for small files. However, it should work (slowly) if you add a pagefile. Let me know if you have other questions.

**Comment by tazr** [comment]
Oh OK, I wouldn't know, thanks. Are there hardware requirements or suggestions for running cmix listed somewhere? I failed to find them. I suppose other people could also be surprised by the amount of memory needed to compress even small files.

**Comment by byronknoll** [comment]
Ah, the memory requirement is listed on the cmix website (
http://www.byronknoll.com/cmix.html) but not in the readme file. I will
update the readme to list that - thanks!
