### ISSUE TITLE
'CC = clang++' fails to compile, seg fault with g++

### ISSUE THREAD

**Issue by 2ahunter** [byronknoll/cmix#43]
With the latest makefile,  I changed CC = clang-3.8 and it fails to compile.  
It compiles fine with CC=g++, as suggested in the README, however I get segmentation faults when I test cmix:

aaron@aaron-HP-EliteBook-840-G1:~/cmpe202/cmix$  ./cmix -n README readme_cmp
Segmentation fault (core dumped)

Any ideas?

**Comment by byronknoll** [comment]
Hi, cmix should work with recent versions of both g++ and clang. What version of g++ are you using? Here are some ideas:

- use a more recent version of g++ or clang
- try compiling with "-O3" instead of "-Ofast -march=native"

**Comment by 2ahunter** [comment]
Thanks--I have g++ 5.4, I think it's the installed version with Ubuntu 16. clang-3.8.  I'll try the '-O3' option first, then update the compilers.

**Comment by 2ahunter** [comment]
upgraded to g++ -7 and compiled with both original makefile and with -O3.  both show a segmentation fault.  I'll try with clang next.

**Comment by 2ahunter** [comment]
Nope, still get segmentation fault.

**Comment by byronknoll** [comment]
Hmm this might be difficult to debug. How much RAM does your computer have? Which OS are you using? If you run cmix without any arguments does it also segfault? When I see a segfault on my own computer I usually use gdb to debug, but that will be difficult if you don't already know how to use gdb.

**Comment by tommythorn** [comment]
Well, it would be fairly useful to simply prefix the invocation with `gdb --args`, typing `run` at the `(gdb) ` prompt, and upon the segfault run `bt` which will give a backtrace.

**Comment by byronknoll** [comment]
I am closing this issue since it hasn't been updated. Feel free to re-open if there are new updates.
