### ISSUE TITLE
Always core dump for all recent versions

### ISSUE THREAD

**Issue by peacherwu** [byronknoll/cmix#44]
I built cmix versions from 13 through 18 obtained here and from [http://www.byronknoll.com/cmix.html](http://www.byronknoll.com/cmix.html) with most recent Clang 6 and g++7. 

Yet they all crash for following compression run:
`./cmix -c d d.cmix`
where `d` is my input file.

Versions 13 and 14 crash with following output:

`terminate called after throwing an instance of 'std::bad_alloc'`
`what():  std::bad_alloc`
`Aborted (core dumped)`

while later versions only has:
`Segmentation fault (core dumped)`

I am using an Ubuntu 16.04 with 8G memory.
Could you help me?

**Comment by byronknoll** [comment]
Hi, I am pretty sure that is due to your computer having too little memory. 32G memory is recommended to run cmix. It is possible to run with less, but you need to have enough swap space. I'll close this issue for now, but feel free to ask additional questions or re-open.

**Comment by peacherwu** [comment]
Thanks a lot for such a prompt reply!
