### ISSUE TITLE
1-billion-word-language-modeling-benchmark-r13output.tar fails on Windows and WSL

### ISSUE THREAD

**Issue by jabowery** [byronknoll/cmix#45]
UPDATE 1/18/2020
The `-n` option seems to work, although after running for a day, progress is only at 0.77%.
END UPDATE

This may be due to the 4,231,823,360 byte length of the tar file.

Here's the output from the WSL binary under an Ubuntu image:

```
$ ../../cmix/cmix -c 1-billion-word-language-modeling-benchmark-r13output.tar out.cmix
4231823360 bytes -> 6 bytes in 5.83 s.
cross entropy: 0.000
```

**Comment by byronknoll** [comment]
Unfortunately I think the max input size supported by cmix right now is 2147483648 bytes. I think your -n workaround also won't have the desired behavior (I suspect it won't compress the entire file).

Thanks for the bug report - I will try to fix this issue when I have time.

**Comment by byronknoll** [comment]
OK, the latest commit should fix this issue.
