### ISSUE TITLE
how to run CMIX on linux

### ISSUE THREAD

**Issue by science-fiktion** [byronknoll/cmix#49]
Hi Knoll,
CMIX is very impressed, compress ratio is several times than rar
I have a short question, how to run CMIX on linux?
read the doc, it only mentioned how to compile cmix on windows
and I tried sudo apt install cmix , but it does not work.
I am not a c++ coder, how can I compile cmix source code on linux system?
thanks!

**Comment by byronknoll** [comment]
If you already have clang (a C++ compiler), you just need to cd into the cmix directory and type "make".

**Comment by science-fiktion** [comment]
CMIX is complied after install gcc, gdb,  base-devel,clang.
the compress and decompress process on linux looks faster than Win10

thanks byronknoll !

**Comment by science-fiktion** [comment]
I compressed a small txt(100k) file on win10( e.g cmix -c english.dic aaa.txt bbb.cmx ), 
I tried to decompress the file bbb.cmx on linux (arch 5.9.16-1)  (cmix -d english.dic bbb.cmx aaa_1.txt)
it took 15 minutes decompress, got aaa_1.txt, but the aaa_1.txt is not matched with original aaa.txt,  aaa_1.txt is filled with junk code, can not readable.
on win10 I used "Windows Executable cmix-v18-windows.zip", on linux I used "Source Code cmix-v18.zip"

**Comment by byronknoll** [comment]
I think this is because the Windows executable and Linux executable were compiled with different options. In the makefile, "-Ofast -march=native" will make cmix run faster, but it might not be compatible with other executables. Compile with "-O3" to fix compatibility issues (at the cost of slower performance).

**Comment by science-fiktion** [comment]
re-compiled CMIX with  "-O3", tried to decompress the file bbb.cmx on linux (arch 5.9.16-1) (e.g cmix -d english.dic bbb.cmx aaa_2.txt)
it took more than 30 minutes(almost twice slower than early version ), got file aaa_2.txt, aaa_2.txt same as aaa_1.txt, it is still not readable

![image](https://user-images.githubusercontent.com/66315424/107142821-b2dbdf00-6931-11eb-947d-782c23757fed.png)

**Comment by byronknoll** [comment]
A couple other ideas:
1) Recompile the Windows executable to match the -O3 used for the Linux one.
2) Try testing compression+decompression both in Linux to see if that works.

**Comment by science-fiktion** [comment]
tried compile with diff parameter， it looks only win10‘s cmix compessed file can be decompressed on win10， arch linux can not decompress correctlly

**Comment by byronknoll** [comment]
That is unfortunate. I am not sure if you want to keep trying to get it working, but another idea is that the compiler is creating the issue:

1) Try compiling in g++ in both Windows and Linux, both with -O3
2) Try compiling with clang++ in both Windows and Linux, both with -O3

There should definitely be some method to get this compatible between computers, but it might be difficult.
