### ISSUE TITLE
Windows binary of cmix v21 doesnt do anything when ran.

### ISSUE THREAD

**Issue by dillfrescott** [byronknoll/cmix#66]
I downloaded cmix v21 from your website and when I try to run it, it just immediately exits for some reason.

![error](https://github.com/user-attachments/assets/b490ff1d-1802-4a10-84a6-ecf5cc6e039b)

**Comment by byronknoll** [comment]
I just uploaded a new version of the windows executable to [www.byronknoll.com/cmix.html](http://www.byronknoll.com/cmix.html) - can you give it another try? This time I statically included libraries when compiling.

**Comment by dillfrescott** [comment]
Ok just downloaded it. its a larger exe file, but still nothing. I tried `cmix.exe --help` and even just `cmix.exe` and nothing sadly.

**Comment by byronknoll** [comment]
hmm, it is difficult to debug further without error messages. If you want to keep trying, one idea is to try running it within cygwin: https://www.cygwin.com/

**Comment by byronknoll** [comment]
Update: I just uploaded a newer version of the executable (compiled with MinGW) which might help with this issue.

**Comment by dillfrescott** [comment]
Sure Ill test it! Thanks!

**Comment by dillfrescott** [comment]
It seems to be working now! Thanks so much for the fix!
