### ISSUE TITLE
Request: Ability to resume interrupted compression/decompression

### ISSUE THREAD

**Issue by dillfrescott** [byronknoll/cmix#68]
Since it usually takes a while to compress and decompress larger files, I feel as though a system to resume compression and decompression if interrupted would be incredibly useful.

Let me know what you think!

**Comment by byronknoll** [comment]
Unfortunately this would be very difficult to implement in cmix, since the models haven't been designed to be serialized to disk (one important difference to the gmix project).

**Comment by dillfrescott** [comment]
Understood!
