### ISSUE TITLE
cmix crashes ubuntu

### ISSUE THREAD

**Issue by shrx** [byronknoll/cmix#8]
I have compiled cmix v11 on Ubuntu 14.04 LTS with `-Ofast -march=native`.
When I try to compress a ~300 MB file, the screen freezes and I have to restart compiz from console.
When I come back to the desktop, the only message in the terminal is: 
```
$ cmix -c test cmix.out
Killed
```

**Comment by byronknoll** [comment]
That sounds like a symptom of running out of memory. How much memory does your computer have? I would recommend trying to monitor the amount of available RAM while cmix runs.

**Comment by shrx** [comment]
Yep I also think it runs out of memory. I couldn't test because it happens instantly when I run the above comman.

**Comment by byronknoll** [comment]
OK, it seems like we have identified the problem. I assume your computer has less than 30GB of available RAM. I will close this issue, but feel free to reopen it if you find something unexpected.

**Comment by gitsilvan** [comment]
The same (pretty much) happens to me when trying to compress a file (even if it's the repository's README) with version 13. The system keeps running, but the output says:

`progress: 0%Killed`

Running Ubuntu on AWS EC2.

**Comment by byronknoll** [comment]
@gitsilvan unfortunately 15GB is not enough RAM to run cmix. Let me know if you still have issues if you get a chance to test this on a computer with more RAM.

**Comment by gitsilvan** [comment]
Oh okay, I thought this wasn't an issue since it works on my local laptop with 8GB RAM—just very, very slowly. Thank you for getting back!

**Comment by byronknoll** [comment]
@gitsilvan It probably works on your laptop due to swap memory (which will be extremely slow). https://blog.metova.com/how-to-enable-swapfile-on-ubuntu-aws-instances/

**Comment by gitsilvan** [comment]
That makes sense. Thank you again for clearing that up.
